import { resolve } from '../src/';

console.log(
  resolve(
    '/js/test-screen',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/bmvp/js/config/screens.js',
  ),
);
console.log(
  resolve(
    '/js/test-screen/constants',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/bmvp/js/config/screens.js',
  ),
);
console.log(
  resolve(
    '../test-screen',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/bmvp/js/config/screens.js',
  ),
);
console.log(
  resolve(
    '/js/test-screen/constants.js',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/bmvp/index.js',
  ),
);
console.log(
  resolve(
    './js/test-screen/constants.js',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/bmvp/index.js',
  ),
);
console.log(
  resolve(
    '/js/test-screen/constants.js',
    '/Users/GrumZ/Documents/H2GLab/Projects/MVP10K/Code/index.js',
  ),
);
